import { http, HttpResponse } from 'msw';

export const handlers = [
  http.get('https://api.github.com/search/users', async ({ request }) => {
    const url = new URL(request.url);
    const q = url.searchParams.get('q');

    if (q === 'octocat') {
      return HttpResponse.json({
        total_count: 1,
        items: [
          {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
            score: 1.0,
          },
        ],
      });
    }

    return HttpResponse.json({
      total_count: 0,
      items: [],
    });
  }),

  http.get('https://api.github.com/users/octocat/repos', () => {
    return HttpResponse.json([
      {
        id: 1296269,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
        name: 'Hello-World',
        full_name: 'octocat/Hello-World',
        private: false,
        owner: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        html_url: 'https://github.com/octocat/Hello-World',
        description: 'My first repository on GitHub!',
        fork: false,
        url: 'https://api.github.com/repos/octocat/Hello-World',
        forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
        keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
        hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
        issue_events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
        events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
        assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
        branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
        tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
        blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
        stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
        contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
        subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
        subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
        commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
        compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
        archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
        issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
        pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
        releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
        deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
        created_at: '2011-01-26T19:06:43Z',
        updated_at: '2024-05-23T12:00:00Z',
        pushed_at: '2024-05-23T12:00:00Z',
        git_url: 'git://github.com/octocat/Hello-World.git',
        ssh_url: 'git@github.com:octocat/Hello-World.git',
        clone_url: 'https://github.com/octocat/Hello-World.git',
        svn_url: 'https://github.com/octocat/Hello-World',
        homepage: null,
        size: 1,
        stargazers_count: 2471,
        watchers_count: 2471,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 1475,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 2,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 1475,
        open_issues: 2,
        watchers: 2471,
        default_branch: 'master',
      },
    ]);
  }),
];